name: Node.js CI/CD -  GCP Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-test-simulate:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Code
      uses: actions/checkout@v3

    - name:  Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name:  Install Dependencies
      run: npm install

    - name:  Run Tests
      run: npm test

    - name:  Build Docker Image
      run: docker build -t s223743838/calculator-app:v1 .

    - name: Image push 
      run: docker push s223743838/calculator-app:v1 

    - name:   GKE Deployment
      run: |
        echo " Build & test successful."
        echo " GKE deployment skipped: service account lacks container.clusters.get"
        echo " Manual deployment verified using:"
        echo "    gcloud container clusters get-credentials sit707-cluster --zone australia-southeast2"
        echo "    kubectl apply -f k8s/deployment.yaml"
        echo "    kubectl logs <pod-name>"
