name: Node.js CI/CD to GCP

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure kubectl for GKE
      run: gcloud container clusters get-credentials sit707-cluster --zone australia-southeast1-a

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and run tests
      run: |
        npm install
        npm test

    - name: Build Docker image
      run: |
        docker build -t s223743838/calculator-app:latest .

    - name: Push Docker image to GCP
      run: |
        gcloud auth configure-docker
        docker push s223743838/calculator-app:latest

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
