name: Node.js CI/CD to GCP

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure kubectl for GKE
      run: gcloud container clusters get-credentials sit707-cluster --region australia-southeast2 --project sit737-25t1-singh-f590599

    - name: Deploy test container to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: Wait for Pod to start
      run: |
        echo "Waiting for pod to be ready..."
        kubectl wait --for=condition=ready pod -l app=calculator-tests --timeout=60s

    - name: Get test logs from pod
      run: |
        POD_NAME=$(kubectl get pods -l app=calculator-tests -o jsonpath="{.items[0].metadata.name}")
        echo "📦 Logs from test pod: $POD_NAME"
        kubectl logs $POD_NAME
